import type { AgeBand, InterestId, Place, TaskCategory } from '../state/types';
import type { Localized } from '../i18n/types';

/**
 * The parts a made for you mission is built out of.
 *
 * The library is fixed and readable, which is its whole value: a parent can
 * look at it and know what their child may be asked to do. But a fixed
 * library of 180 missions runs out, and it can never be about the one thing
 * this particular child cares about. So there is a second source: skeletons
 * with holes in them, and banks of pieces to fill the holes with, chosen by
 * what the child has liked.
 *
 * It is a grammar, not a model. Nothing is generated by a network, nothing
 * is fetched, and there is no key: the whole thing runs on the phone in
 * aeroplane mode, which matters for an app whose point is putting the phone
 * down. A parent can still be shown every skeleton and every piece, so the
 * promise that nobody knows what the app might say to their child is kept.
 *
 * -------------------------------------------------------------------------
 * THE RULE FOR ANYONE ADDING A PIECE
 *
 * Turkish and Azerbaijani inflect where English uses a preposition, so a
 * bank cannot hold bare nouns and expect them to fit. Each bank has exactly
 * one job in a sentence, and every piece in it is written already in the
 * form that job needs:
 *
 *   thing    a bare noun, as a direct object with no case ending:
 *            "qaşıq" / "kaşık" / "spoon". `many` is the form after a number,
 *            which English pluralises and the other two do not.
 *   place    a complete locative phrase: "mətbəxdə" / "mutfakta" /
 *            "in the kitchen". Never just the room.
 *   move     an imperative verb: "tullan" / "zıpla" / "hop".
 *   twist    a complete adverbial phrase: "heç səs çıxarmadan" /
 *            "hiç ses çıkarmadan" / "without making a sound".
 *   theme    a complete comparison: "bir astronavt kimi" / "bir astronot
 *            gibi" / "like an astronaut".
 *   person   a complete phrase including the postposition: "evdəki biri ilə"
 *            / "evdeki biriyle" / "with someone at home".
 *   subject  a direct object in the accusative: "ən çox sevdiyin heyvanı" /
 *            "en sevdiğin hayvanı" / "your favourite animal". It only ever
 *            follows a verb that takes an object. Never put a postposition
 *            after it: "heyvanı haqqında" is wrong in both languages.
 *
 * Write the sentence out in all three languages before adding it. A piece
 * that only reads well in one of them is a bug in the other two, and
 * `npm run test:spark` checks that text exists, not that it is good.
 *
 * The tags are what stop the grammar from producing nonsense that parses:
 * `places` keeps cushions out of the kitchen, `maxCount` keeps the hunt from
 * asking for nine teddy bears, and the tag a skeleton demands keeps a
 * painter out of a sentence about building a bridge.
 */

export type SlotKind = 'thing' | 'place' | 'move' | 'twist' | 'theme' | 'person' | 'subject';

export type Filler = {
  id: string;
  text: Localized;
  /** The form used after a number. English pluralises; the others do not. */
  many?: Localized;
  /** What this piece is good for, matched against a skeleton's `needs`. */
  tags?: string[];
  /** Interests it carries into the finished mission. */
  interests?: InterestId[];
  /** Ages it reads right for. Missing means all of them. */
  bands?: AgeBand[];
  /** Replaces the skeleton's emoji when this piece is the star of it. */
  emoji?: string;
  /**
   * Place ids this piece belongs with. Missing means anywhere. It works in
   * both directions: a piece drawn first narrows which places are left, and
   * a place drawn first narrows the pieces.
   */
  places?: string[];
  /** Most of this there could plausibly be in one home. */
  maxCount?: number;
};

/**
 * A skeleton with holes in it.
 *
 * `title` and `body` carry `{{slot}}` markers, filled by `engine/spark.ts`.
 * `{{things}}` uses the plural form, `{{count}}` the drawn number.
 */
export type SparkTemplate = {
  id: string;
  /** One band each: the register and the length are not portable between them. */
  band: AgeBand;
  category: TaskCategory;
  minutes: number;
  stars: number;
  emoji: string;
  title: Localized;
  body: Localized;
  steps?: Localized[];
  /** Interests it always carries, on top of whatever its pieces bring. */
  interests?: InterestId[];
  place?: Place;
  /** Only ever `photo`; a made mission never asks for motion it cannot spec. */
  proof?: 'tap' | 'photo';
  /** A number the child reports at the end, with `{{slot}}` markers allowed. */
  ask?: { question: Localized; min: number; max: number; goalFromCount?: boolean };
  /** Ages 10-14 only: something written in their own words. */
  note?: { prompt: Localized; lines?: number; minChars?: number };
  /** The number drawn for `{{count}}`. */
  count?: { min: number; max: number };
  /** Tags a piece must carry to be allowed into a given slot. */
  needs?: Partial<Record<SlotKind, string[]>>;
  /** Tags that rule a piece out, for the cases a required tag cannot express. */
  avoids?: Partial<Record<SlotKind, string[]>>;
  /**
   * `none` turns off the movement check a moving skeleton would otherwise
   * get, for the ones that already prove themselves another way. A hunt in
   * the park is an outdoor mission with a photo and a count at the end;
   * demanding a step total on top of that only sends honest work to a parent.
   */
  measure?: 'none';
};

/* ------------------------------------------------------------------ pieces */


const SOFT_ROOMS = ['home', 'living', 'yourroom', 'bed', 'undertable'];
const OUTSIDE = ['garden', 'park', 'balcony'];

const things: Filler[] = [
  {
    id: 'spoon',
    text: { az: 'qaşıq', tr: 'kaşık', en: 'spoon' },
    many: { az: 'qaşıq', tr: 'kaşık', en: 'spoons' },
    tags: ['many', 'tidy', 'small', 'build', 'sortable'],
    interests: ['cooking'],
    places: ['home', 'kitchen', 'living', 'undertable'],
    emoji: '🥄',
  },
  {
    id: 'sock',
    text: { az: 'corab', tr: 'çorap', en: 'sock' },
    many: { az: 'corab', tr: 'çorap', en: 'socks' },
    tags: ['many', 'tidy', 'small'],
    places: ['home', 'yourroom', 'bed', 'hallway', 'door', 'undertable'],
    emoji: '🧦',
  },
  {
    id: 'book',
    text: { az: 'kitab', tr: 'kitap', en: 'book' },
    many: { az: 'kitab', tr: 'kitap', en: 'books' },
    tags: ['many', 'tidy', 'build', 'sortable'],
    interests: ['books'],
    places: ['home', 'living', 'yourroom', 'bed', 'window', 'undertable'],
    emoji: '📚',
  },
  {
    id: 'cushion',
    text: { az: 'yastıq', tr: 'yastık', en: 'cushion' },
    many: { az: 'yastıq', tr: 'yastık', en: 'cushions' },
    tags: ['tidy', 'build'],
    interests: ['building'],
    places: SOFT_ROOMS,
    maxCount: 5,
    emoji: '🛋️',
  },
  {
    id: 'cup',
    text: { az: 'stəkan', tr: 'bardak', en: 'cup' },
    many: { az: 'stəkan', tr: 'bardak', en: 'cups' },
    tags: ['many', 'tidy', 'small', 'build', 'sortable'],
    interests: ['cooking'],
    places: ['home', 'kitchen', 'living'],
    emoji: '🥤',
  },
  {
    id: 'towel',
    text: { az: 'dəsmal', tr: 'havlu', en: 'towel' },
    many: { az: 'dəsmal', tr: 'havlu', en: 'towels' },
    tags: ['many', 'tidy'],
    places: ['home', 'kitchen', 'yourroom'],
    maxCount: 5,
    emoji: '🧺',
  },
  {
    id: 'box',
    text: { az: 'qutu', tr: 'kutu', en: 'box' },
    many: { az: 'qutu', tr: 'kutu', en: 'boxes' },
    tags: ['many', 'build', 'craft', 'tidy', 'sortable'],
    interests: ['building'],
    places: ['home', 'hallway', 'yourroom', 'living', 'door'],
    maxCount: 6,
    emoji: '📦',
  },
  {
    id: 'pencil',
    text: { az: 'karandaş', tr: 'kalem', en: 'pencil' },
    many: { az: 'karandaş', tr: 'kalem', en: 'pencils' },
    tags: ['many', 'tidy', 'small', 'draw', 'sortable'],
    interests: ['drawing'],
    places: ['home', 'yourroom', 'living', 'window', 'undertable'],
    emoji: '✏️',
  },
  {
    id: 'crayon',
    text: { az: 'rəngli karandaş', tr: 'boya kalemi', en: 'crayon' },
    many: { az: 'rəngli karandaş', tr: 'boya kalemi', en: 'crayons' },
    tags: ['many', 'small', 'draw', 'sortable'],
    interests: ['drawing'],
    places: ['home', 'yourroom', 'living', 'undertable'],
    emoji: '🖍️',
  },
  {
    id: 'ball',
    text: { az: 'top', tr: 'top', en: 'ball' },
    many: { az: 'top', tr: 'top', en: 'balls' },
    tags: ['small'],
    interests: ['football'],
    places: ['home', 'yourroom', 'garden', 'park'],
    maxCount: 3,
    emoji: '⚽',
  },
  {
    id: 'toycar',
    text: { az: 'oyuncaq maşın', tr: 'oyuncak araba', en: 'toy car' },
    many: { az: 'oyuncaq maşın', tr: 'oyuncak araba', en: 'toy cars' },
    tags: ['many', 'tidy', 'small', 'sortable'],
    bands: ['3-5', '6-9'],
    places: SOFT_ROOMS,
    maxCount: 6,
    emoji: '🚗',
  },
  {
    id: 'teddy',
    text: { az: 'oyuncaq ayı', tr: 'oyuncak ayı', en: 'teddy bear' },
    many: { az: 'oyuncaq ayı', tr: 'oyuncak ayı', en: 'teddy bears' },
    tags: ['tidy'],
    interests: ['animals'],
    bands: ['3-5', '6-9'],
    places: SOFT_ROOMS,
    maxCount: 4,
    emoji: '🧸',
  },
  {
    id: 'block',
    text: { az: 'lego hissəsi', tr: 'lego parçası', en: 'building block' },
    many: { az: 'lego hissəsi', tr: 'lego parçası', en: 'building blocks' },
    tags: ['many', 'build', 'tidy', 'small', 'sortable'],
    interests: ['building'],
    bands: ['3-5', '6-9'],
    places: SOFT_ROOMS,
    emoji: '🧱',
  },
  {
    id: 'plant',
    text: { az: 'dibçək gülü', tr: 'saksı bitkisi', en: 'plant' },
    many: { az: 'dibçək gülü', tr: 'saksı bitkisi', en: 'plants' },
    tags: [],
    interests: ['nature'],
    places: ['home', 'window', 'balcony', 'living', 'garden'],
    maxCount: 3,
    emoji: '🪴',
  },
  {
    id: 'shoe',
    text: { az: 'ayaqqabı', tr: 'ayakkabı', en: 'shoe' },
    many: { az: 'ayaqqabı', tr: 'ayakkabı', en: 'shoes' },
    tags: ['many', 'tidy', 'sortable'],
    places: ['home', 'hallway', 'door', 'yourroom'],
    maxCount: 8,
    emoji: '👟',
  },
  {
    id: 'bottle',
    text: { az: 'plastik butulka', tr: 'plastik şişe', en: 'plastic bottle' },
    many: { az: 'plastik butulka', tr: 'plastik şişe', en: 'plastic bottles' },
    tags: ['many', 'tidy', 'build', 'craft', 'small', 'sortable'],
    places: ['home', 'kitchen', 'living', 'yourroom'],
    maxCount: 6,
    emoji: '🧴',
  },
  {
    id: 'leaf',
    text: { az: 'yarpaq', tr: 'yaprak', en: 'leaf' },
    many: { az: 'yarpaq', tr: 'yaprak', en: 'leaves' },
    tags: ['many', 'small', 'nature', 'sortable'],
    interests: ['nature'],
    places: OUTSIDE,
    emoji: '🍃',
  },
  {
    id: 'stone',
    text: { az: 'daş', tr: 'taş', en: 'stone' },
    many: { az: 'daş', tr: 'taş', en: 'stones' },
    tags: ['many', 'small', 'nature', 'build', 'sortable'],
    interests: ['nature'],
    places: OUTSIDE,
    emoji: '🪨',
  },
  {
    id: 'feather',
    text: { az: 'lələk', tr: 'tüy', en: 'feather' },
    many: { az: 'lələk', tr: 'tüy', en: 'feathers' },
    tags: ['small', 'nature'],
    interests: ['nature', 'animals'],
    places: OUTSIDE,
    maxCount: 4,
    emoji: '🪶',
  },
  {
    id: 'blanket',
    text: { az: 'yorğan', tr: 'battaniye', en: 'blanket' },
    many: { az: 'yorğan', tr: 'battaniye', en: 'blankets' },
    tags: ['tidy', 'build'],
    interests: ['building'],
    places: SOFT_ROOMS,
    maxCount: 3,
    emoji: '🛏️',
  },
  {
    id: 'chair',
    text: { az: 'stul', tr: 'sandalye', en: 'chair' },
    many: { az: 'stul', tr: 'sandalye', en: 'chairs' },
    tags: ['build'],
    interests: ['building'],
    places: ['home', 'kitchen', 'living', 'yourroom'],
    maxCount: 4,
    emoji: '🪑',
  },
  {
    id: 'fork',
    text: { az: 'çəngəl', tr: 'çatal', en: 'fork' },
    many: { az: 'çəngəl', tr: 'çatal', en: 'forks' },
    tags: ['many', 'tidy', 'small'],
    interests: ['cooking'],
    places: ['home', 'kitchen'],
    emoji: '🍴',
  },
  {
    id: 'card',
    text: { az: 'karton parçası', tr: 'karton parçası', en: 'piece of cardboard' },
    many: { az: 'karton parçası', tr: 'karton parçası', en: 'pieces of cardboard' },
    tags: ['many', 'build', 'craft', 'small'],
    interests: ['building'],
    places: ['home', 'kitchen', 'yourroom', 'living'],
    maxCount: 6,
    emoji: '📦',
  },
  {
    id: 'paper',
    text: { az: 'kağız', tr: 'kağıt', en: 'sheet of paper' },
    many: { az: 'kağız', tr: 'kağıt', en: 'sheets of paper' },
    tags: ['many', 'craft', 'draw', 'small'],
    interests: ['drawing'],
    places: ['home', 'yourroom', 'living', 'window'],
    emoji: '📄',
  },
  {
    id: 'string',
    text: { az: 'ip', tr: 'ip', en: 'piece of string' },
    many: { az: 'ip', tr: 'ip', en: 'pieces of string' },
    tags: ['craft', 'small'],
    places: ['home', 'kitchen', 'yourroom'],
    maxCount: 4,
    emoji: '🧵',
  },
  {
    id: 'torch',
    text: { az: 'fənər', tr: 'el feneri', en: 'torch' },
    many: { az: 'fənər', tr: 'el feneri', en: 'torches' },
    tags: ['small'],
    interests: ['science', 'space'],
    places: ['home', 'yourroom', 'living', 'hallway'],
    maxCount: 2,
    emoji: '🔦',
  },
  {
    id: 'key',
    text: { az: 'açar', tr: 'anahtar', en: 'key' },
    many: { az: 'açar', tr: 'anahtar', en: 'keys' },
    tags: ['small', 'tidy'],
    places: ['home', 'hallway', 'door', 'living'],
    maxCount: 4,
    emoji: '🔑',
  },
];

const places: Filler[] = [
  {
    id: 'home',
    text: { az: 'evdə', tr: 'evde', en: 'at home' },
    tags: ['indoor', 'roomy', 'room'],
  },
  {
    id: 'kitchen',
    text: { az: 'mətbəxdə', tr: 'mutfakta', en: 'in the kitchen' },
    tags: ['indoor', 'room'],
    interests: ['cooking'],
  },
  {
    id: 'living',
    text: { az: 'qonaq otağında', tr: 'oturma odasında', en: 'in the living room' },
    tags: ['indoor', 'roomy', 'room'],
  },
  {
    id: 'yourroom',
    text: { az: 'öz otağında', tr: 'kendi odanda', en: 'in your room' },
    tags: ['indoor', 'roomy', 'room'],
  },
  {
    id: 'hallway',
    text: { az: 'dəhlizdə', tr: 'koridorda', en: 'in the hallway' },
    tags: ['indoor', 'roomy', 'room'],
  },
  {
    id: 'window',
    text: { az: 'pəncərənin yanında', tr: 'pencerenin yanında', en: 'by the window' },
    tags: ['indoor'],
  },
  {
    id: 'undertable',
    text: { az: 'masanın altında', tr: 'masanın altında', en: 'under the table' },
    tags: ['indoor'],
  },
  {
    id: 'bed',
    text: { az: 'çarpayının yanında', tr: 'yatağının yanında', en: 'next to your bed' },
    tags: ['indoor'],
  },
  {
    id: 'balcony',
    text: { az: 'balkonda', tr: 'balkonda', en: 'on the balcony' },
    tags: ['indoor'],
    interests: ['nature'],
  },
  {
    id: 'garden',
    text: { az: 'həyətdə', tr: 'bahçede', en: 'in the garden' },
    tags: ['outdoor', 'roomy', 'kickable'],
    interests: ['nature'],
  },
  {
    id: 'park',
    text: { az: 'parkda', tr: 'parkta', en: 'at the park' },
    tags: ['outdoor', 'roomy', 'kickable'],
    interests: ['nature'],
  },
  {
    id: 'stairs',
    text: { az: 'pilləkənlərdə', tr: 'merdivenlerde', en: 'on the stairs' },
    tags: ['indoor'],
  },
  {
    id: 'door',
    text: { az: 'qapının qarşısında', tr: 'kapının önünde', en: 'in front of the door' },
    tags: ['indoor'],
  },
];

const moves: Filler[] = [
  {
    id: 'hop',
    text: { az: 'tullan', tr: 'zıpla', en: 'hop' },
    tags: ['rep'],
    emoji: '🦘',
  },
  {
    id: 'spin',
    text: { az: 'fırlan', tr: 'kendi etrafında dön', en: 'spin around' },
    tags: ['rep'],
    emoji: '🌀',
  },
  {
    id: 'squat',
    text: { az: 'otur-qalx', tr: 'çömel ve kalk', en: 'squat' },
    tags: ['rep'],
    bands: ['6-9', '10-14'],
    emoji: '🏋️',
  },
  {
    id: 'toes',
    text: {
      az: 'ayaq barmaqlarına toxun',
      tr: 'ayak parmaklarına dokun',
      en: 'touch your toes',
    },
    tags: ['rep'],
    emoji: '🤸',
  },
  {
    id: 'clap',
    text: {
      az: 'başının üstündə əl çal',
      tr: 'başının üstünde alkış yap',
      en: 'clap over your head',
    },
    tags: ['rep'],
    interests: ['music'],
    emoji: '👏',
  },
  {
    id: 'starjump',
    text: { az: 'ulduz tullanışı et', tr: 'yıldız zıplaması yap', en: 'do a star jump' },
    tags: ['rep'],
    emoji: '⭐',
  },
  {
    id: 'kick',
    text: { az: 'topa vur', tr: 'topa vur', en: 'kick the ball' },
    tags: ['rep'],
    interests: ['football'],
    // Not in a hallway, and not in anybody's living room.
    places: ['garden', 'park'],
    emoji: '⚽',
  },
  {
    id: 'dancestep',
    text: { az: 'rəqs addımı at', tr: 'dans adımı at', en: 'take a dance step' },
    tags: ['rep'],
    interests: ['dance', 'music'],
    emoji: '💃',
  },
  {
    id: 'crab',
    text: { az: 'xərçəng kimi addımla', tr: 'yengeç gibi adım at', en: 'take a crab step' },
    tags: ['rep'],
    interests: ['animals'],
    bands: ['3-5', '6-9'],
    emoji: '🦀',
  },
  {
    id: 'frog',
    text: { az: 'qurbağa kimi tullan', tr: 'kurbağa gibi zıpla', en: 'jump like a frog' },
    tags: ['rep'],
    interests: ['animals'],
    bands: ['3-5', '6-9'],
    emoji: '🐸',
  },
  {
    id: 'rocket',
    text: { az: 'raket kimi tullan', tr: 'roket gibi zıpla', en: 'jump like a rocket' },
    tags: ['rep'],
    interests: ['space'],
    bands: ['3-5', '6-9'],
    emoji: '🚀',
  },
  {
    id: 'lunge',
    text: { az: 'irəli addım at və otur', tr: 'öne adım atıp çök', en: 'do a lunge' },
    tags: ['rep'],
    bands: ['10-14'],
    emoji: '🦵',
  },
];

/**
 * `rule` twists are a condition on how the whole thing is done. `order`
 * twists say how a row of things should end up. They are not interchangeable:
 * "line them up using only the blue ones" is not an instruction.
 */
const twists: Filler[] = [
  {
    id: 'silent',
    text: { az: 'heç səs çıxarmadan', tr: 'hiç ses çıkarmadan', en: 'without making a sound' },
    tags: ['rule'],
  },
  {
    id: 'onehand',
    text: { az: 'yalnız bir əlinlə', tr: 'sadece tek elinle', en: 'using only one hand' },
    tags: ['rule'],
  },
  {
    id: 'backwards',
    text: { az: 'geri-geri yeriyərək', tr: 'geri geri yürüyerek', en: 'walking backwards' },
    tags: ['rule'],
  },
  {
    id: 'slowmo',
    text: { az: 'ləng hərəkətlə', tr: 'ağır çekimde', en: 'in slow motion' },
    tags: ['rule'],
  },
  {
    id: 'twomin',
    text: {
      az: 'iki dəqiqədən az vaxtda',
      tr: 'iki dakikadan kısa sürede',
      en: 'in under two minutes',
    },
    tags: ['rule'],
  },
  {
    id: 'tiptoe',
    text: { az: 'barmaqlarının ucunda', tr: 'parmak ucunda', en: 'on tiptoe' },
    tags: ['rule'],
  },
  {
    id: 'nolaugh',
    text: { az: 'gülmədən', tr: 'hiç gülmeden', en: 'without laughing' },
    tags: ['rule'],
  },
  {
    id: 'singing',
    text: { az: 'mahnı oxuya-oxuya', tr: 'şarkı söyleyerek', en: 'while singing' },
    tags: ['rule'],
    interests: ['music'],
  },
  {
    id: 'bysize',
    text: {
      az: 'böyükdən kiçiyə',
      tr: 'büyükten küçüğe',
      en: 'biggest to smallest',
    },
    tags: ['order'],
  },
  {
    id: 'bysizeup',
    text: { az: 'kiçikdən böyüyə', tr: 'küçükten büyüğe', en: 'smallest to biggest' },
    tags: ['order'],
  },
  {
    id: 'bycolour',
    text: { az: 'rənginə görə', tr: 'rengine göre', en: 'by colour' },
    tags: ['order'],
  },
  {
    id: 'byage',
    text: {
      az: 'ən köhnədən ən təzəyə',
      tr: 'en eskiden en yeniye',
      en: 'oldest to newest',
    },
    tags: ['order'],
    bands: ['6-9', '10-14'],
  },
];

/**
 * `maker` themes can build something. `act` themes can be walked around as.
 * A painter cannot build a bridge and an engineer is a dull thing to pretend
 * to be, so the skeletons ask for one or the other.
 */
const themes: Filler[] = [
  {
    id: 'astronaut',
    text: { az: 'bir astronavt kimi', tr: 'bir astronot gibi', en: 'like an astronaut' },
    tags: ['maker', 'act'],
    interests: ['space'],
    emoji: '🚀',
  },
  {
    id: 'detective',
    text: { az: 'bir dedektiv kimi', tr: 'bir dedektif gibi', en: 'like a detective' },
    tags: ['act'],
    interests: ['science'],
    emoji: '🔎',
  },
  {
    id: 'chef',
    text: { az: 'bir aşpaz kimi', tr: 'bir şef gibi', en: 'like a chef' },
    // Not a maker: a chef building a tower out of blankets is the kind of
    // sentence that makes the whole feature look automatic.
    tags: ['act'],
    interests: ['cooking'],
    emoji: '🍳',
  },
  {
    id: 'explorer',
    text: { az: 'bir kəşfiyyatçı kimi', tr: 'bir kaşif gibi', en: 'like an explorer' },
    tags: ['act'],
    interests: ['nature'],
    emoji: '🧭',
  },
  {
    id: 'vet',
    text: { az: 'bir baytar kimi', tr: 'bir veteriner gibi', en: 'like a vet' },
    tags: ['act'],
    interests: ['animals'],
    emoji: '🐾',
  },
  {
    id: 'engineer',
    text: { az: 'bir mühəndis kimi', tr: 'bir mühendis gibi', en: 'like an engineer' },
    tags: ['maker'],
    interests: ['building'],
    emoji: '🔧',
  },
  {
    id: 'dancer',
    text: { az: 'bir rəqs ulduzu kimi', tr: 'bir dans yıldızı gibi', en: 'like a dancer' },
    tags: ['act'],
    interests: ['dance'],
    emoji: '💃',
  },
  {
    id: 'keeper',
    text: { az: 'bir qapıçı kimi', tr: 'bir kaleci gibi', en: 'like a goalkeeper' },
    tags: ['act'],
    interests: ['football'],
    emoji: '🧤',
  },
  {
    id: 'architect',
    text: { az: 'bir memar kimi', tr: 'bir mimar gibi', en: 'like an architect' },
    tags: ['maker'],
    interests: ['building', 'drawing'],
    emoji: '📐',
  },
  {
    id: 'captain',
    text: { az: 'bir kapitan kimi', tr: 'bir kaptan gibi', en: 'like a captain' },
    tags: ['maker', 'act'],
    emoji: '⚓',
  },
  {
    id: 'robot',
    text: { az: 'bir robot kimi', tr: 'bir robot gibi', en: 'like a robot' },
    tags: ['maker', 'act'],
    bands: ['3-5', '6-9'],
    emoji: '🤖',
  },
];

const people: Filler[] = [
  {
    id: 'someone',
    text: { az: 'evdəki biri ilə', tr: 'evdeki biriyle', en: 'with someone at home' },
  },
  {
    id: 'grownup',
    text: { az: 'bir böyüklə', tr: 'bir büyüğünle', en: 'with a grown up' },
  },
  {
    id: 'sibling',
    text: {
      az: 'bacın və ya qardaşınla',
      tr: 'kardeşinle',
      en: 'with your brother or sister',
    },
  },
  {
    id: 'friend',
    text: { az: 'bir dostunla', tr: 'bir arkadaşınla', en: 'with a friend' },
    bands: ['6-9', '10-14'],
  },
];

/**
 * `draw` subjects can be drawn, `tell` subjects can carry a story, `work`
 * subjects are things a teenager can actually sit down and get on with.
 */
const subjects: Filler[] = [
  {
    id: 'animal',
    text: {
      az: 'ən çox sevdiyin heyvanı',
      tr: 'en sevdiğin hayvanı',
      en: 'your favourite animal',
    },
    tags: ['draw', 'tell'],
    interests: ['animals'],
    emoji: '🐾',
  },
  {
    id: 'planet',
    text: {
      az: 'heç kimin tapmadığı bir planeti',
      tr: 'kimsenin bulmadığı bir gezegeni',
      en: 'a planet nobody has found',
    },
    tags: ['draw', 'tell'],
    interests: ['space'],
    emoji: '🪐',
  },
  {
    id: 'view',
    text: {
      az: 'pəncərədən görünən mənzərəni',
      tr: 'pencereden görünen manzarayı',
      en: 'the view from your window',
    },
    tags: ['draw'],
    interests: ['nature'],
    emoji: '🖼️',
  },
  {
    id: 'machine',
    text: {
      az: 'səhər yeməyi hazırlayan bir maşını',
      tr: 'kahvaltı hazırlayan bir makineyi',
      en: 'a machine that makes breakfast',
    },
    tags: ['draw', 'tell'],
    interests: ['building', 'science'],
    emoji: '⚙️',
  },
  {
    id: 'funniest',
    text: {
      az: 'bugünün ən gülməli anını',
      tr: 'bugünün en komik anını',
      en: 'the funniest moment of today',
    },
    tags: ['draw', 'tell'],
    emoji: '😄',
  },
  {
    id: 'map',
    text: { az: 'evinizin xəritəsini', tr: 'evinizin haritasını', en: 'a map of your home' },
    tags: ['draw'],
    interests: ['building'],
    emoji: '🗺️',
  },
  {
    id: 'cover',
    text: {
      az: 'sevdiyin mahnı üçün bir üz qabığı',
      tr: 'sevdiğin bir şarkı için bir kapak',
      en: 'a cover for a song you love',
    },
    tags: ['draw'],
    interests: ['music', 'drawing'],
    emoji: '🎵',
  },
  {
    id: 'monster',
    text: { az: 'mehriban bir canavarı', tr: 'sevimli bir canavarı', en: 'a friendly monster' },
    tags: ['draw', 'tell'],
    bands: ['3-5', '6-9'],
    emoji: '👾',
  },
  {
    id: 'hero',
    text: {
      az: 'heç vaxt qorxmayan birini',
      tr: 'hiç korkmayan birini',
      en: 'somebody who is never afraid',
    },
    tags: ['draw', 'tell'],
    bands: ['3-5', '6-9'],
    emoji: '🦸',
  },
  {
    id: 'route',
    text: {
      az: 'velosipedlə getdiyin yolu',
      tr: 'bisikletle gittiğin yolu',
      en: 'the route you ride',
    },
    tags: ['draw'],
    interests: ['bike'],
    bands: ['6-9', '10-14'],
    emoji: '🚲',
  },
  {
    id: 'skill',
    text: {
      az: 'öyrənmək istədiyin bir bacarığı',
      tr: 'öğrenmek istediğin bir beceriyi',
      en: 'a skill you want to learn',
    },
    tags: ['work'],
    bands: ['10-14'],
    emoji: '🎯',
  },
  {
    id: 'putoff',
    text: {
      az: 'təxirə saldığın bir işi',
      tr: 'sürekli ertelediğin bir işi',
      en: 'something you keep putting off',
    },
    tags: ['work'],
    bands: ['10-14'],
    emoji: '⏳',
  },
  {
    id: 'subjectstudy',
    text: {
      az: 'ən çətin gələn dərsi',
      tr: 'en zorlandığın dersi',
      en: 'the subject you find hardest',
    },
    tags: ['work'],
    bands: ['10-14'],
    emoji: '📐',
  },
  {
    id: 'ownproject',
    text: {
      az: 'öz başladığın bir işi',
      tr: 'kendi başlattığın bir işi',
      en: 'something you started yourself',
    },
    tags: ['work'],
    bands: ['10-14'],
    emoji: '🧩',
  },
];

export const slotBanks: Record<SlotKind, Filler[]> = {
  thing: things,
  place: places,
  move: moves,
  twist: twists,
  theme: themes,
  person: people,
  subject: subjects,
};

/* --------------------------------------------------------------- skeletons */

export const sparkTemplates: SparkTemplate[] = [
  /* ----------------------------------------------------------------- 3 to 5 */
  {
    id: 'l-find',
    band: '3-5',
    category: 'move',
    minutes: 6,
    stars: 6,
    emoji: '🔍',
    count: { min: 2, max: 5 },
    needs: { thing: ['many'], place: ['indoor'] },
    title: {
      az: '{{count}} {{thing}} tap',
      tr: '{{count}} {{thing}} bul',
      en: 'Find {{count}} {{things}}',
    },
    body: {
      az: '{{place}} {{count}} {{thing}} tap və hamısını bir yerə yığ.',
      tr: '{{place}} {{count}} {{thing}} bul ve hepsini bir araya getir.',
      en: 'Find {{count}} {{things}} {{place}} and put them all in one pile.',
    },
  },
  {
    id: 'l-reps',
    band: '3-5',
    category: 'move',
    minutes: 5,
    stars: 5,
    emoji: '🦘',
    count: { min: 5, max: 12 },
    needs: { move: ['rep'], place: ['roomy'] },
    title: { az: '{{count}} dəfə', tr: '{{count}} kere', en: '{{count}} times' },
    body: {
      az: '{{place}} {{count}} dəfə {{move}}. Ucadan say.',
      tr: '{{place}} {{count}} kere {{move}}. Yüksek sesle say.',
      en: '{{move}} {{count}} times {{place}}. Count out loud.',
    },
  },
  {
    id: 'l-tower',
    band: '3-5',
    category: 'create',
    minutes: 8,
    stars: 8,
    emoji: '🧱',
    proof: 'photo',
    count: { min: 3, max: 6 },
    needs: { thing: ['build'] },
    title: { az: '{{thing}} qülləsi', tr: '{{thing}} kulesi', en: 'A tower of {{things}}' },
    body: {
      az: '{{count}} {{thing}} üst-üstə qoy. Yıxılmasa, bir dənə də əlavə et.',
      tr: '{{count}} {{thing}} üst üste koy. Yıkılmazsa bir tane daha ekle.',
      en: 'Stack {{count}} {{things}} on top of each other. If it stays up, add one more.',
    },
  },
  {
    id: 'l-draw',
    band: '3-5',
    category: 'create',
    minutes: 10,
    stars: 10,
    emoji: '🎨',
    proof: 'photo',
    interests: ['drawing'],
    needs: { subject: ['draw'] },
    title: { az: 'Bunu çək', tr: 'Bunu çiz', en: 'Draw this' },
    body: {
      az: '{{subject}} çək. İstədiyin rəngi seç.',
      tr: '{{subject}} çiz. İstediğin rengi seç.',
      en: 'Draw {{subject}}. Any colours you like.',
    },
  },
  {
    id: 'l-tidy',
    band: '3-5',
    category: 'calm',
    minutes: 6,
    stars: 6,
    emoji: '🧹',
    count: { min: 3, max: 6 },
    needs: { thing: ['tidy'], place: ['indoor'] },
    title: { az: 'Yerinə qoy', tr: 'Yerine koy', en: 'Put them back' },
    body: {
      az: '{{place}} {{count}} {{thing}} tap və hər birini öz yerinə qoy.',
      tr: '{{place}} {{count}} {{thing}} bul ve her birini yerine koy.',
      en: 'Find {{count}} {{things}} {{place}} and put each one back where it lives.',
    },
  },
  {
    id: 'l-pretend',
    band: '3-5',
    category: 'social',
    minutes: 7,
    stars: 7,
    emoji: '🎭',
    needs: { place: ['roomy'], theme: ['act'] },
    title: { az: 'Bir az rol oyna', tr: 'Biraz rol yap', en: 'Pretend for a bit' },
    body: {
      az: '{{place}} {{theme}} gəz. Sonra kiməsə göstər.',
      tr: '{{place}} {{theme}} dolaş. Sonra birine göster.',
      en: 'Move around {{place}} {{theme}}. Then show someone.',
    },
  },
  {
    id: 'l-sort',
    band: '3-5',
    category: 'calm',
    minutes: 7,
    stars: 7,
    emoji: '📏',
    count: { min: 3, max: 6 },
    needs: { thing: ['sortable', 'small'], twist: ['order'] },
    title: { az: 'Sıraya düz', tr: 'Sıraya diz', en: 'Line them up' },
    body: {
      az: '{{count}} {{thing}} tap və onları {{twist}} düz.',
      tr: '{{count}} {{thing}} bul ve onları {{twist}} diz.',
      en: 'Find {{count}} {{things}} and line them up {{twist}}.',
    },
  },
  {
    id: 'l-together',
    band: '3-5',
    category: 'social',
    minutes: 8,
    stars: 8,
    emoji: '🤝',
    count: { min: 4, max: 8 },
    needs: { move: ['rep'] },
    title: { az: 'Birlikdə', tr: 'Birlikte', en: 'Together' },
    body: {
      az: '{{person}} {{count}} dəfə {{move}}. Növbə ilə sayın.',
      tr: '{{person}} {{count}} kere {{move}}. Sırayla sayın.',
      en: '{{move}} {{count}} times {{person}}. Take turns counting.',
    },
  },

  /* ----------------------------------------------------------------- 6 to 9 */
  {
    id: 'j-hunt',
    band: '6-9',
    category: 'move',
    minutes: 10,
    stars: 10,
    emoji: '🔎',
    count: { min: 4, max: 9 },
    needs: { thing: ['many'], place: ['indoor'], twist: ['rule'] },
    ask: {
      question: {
        az: 'Neçə dənə tapdın?',
        tr: 'Kaç tane buldun?',
        en: 'How many did you find?',
      },
      min: 0,
      max: 20,
      goalFromCount: true,
    },
    title: { az: 'Axtarış: {{thing}}', tr: 'Arama: {{thing}}', en: 'Hunt: {{things}}' },
    body: {
      az: '{{place}} {{count}} {{thing}} tap. Bir şərt var: {{twist}}.',
      tr: '{{place}} {{count}} {{thing}} bul. Bir şart var: {{twist}}.',
      en: 'Find {{count}} {{things}} {{place}}. One rule: {{twist}}.',
    },
    steps: [
      {
        az: 'Başlamazdan əvvəl haraya baxacağını fikirləş.',
        tr: 'Başlamadan önce nereye bakacağını düşün.',
        en: 'Before you start, think about where to look.',
      },
      {
        az: 'Tapdıqlarını bir yerə yığ ki, saya biləsən.',
        tr: 'Bulduklarını bir yere koy ki sayabilesin.',
        en: 'Put what you find in one place so you can count it.',
      },
      {
        az: 'Sayını yadda saxla, sonda soruşacağam.',
        tr: 'Sayıyı aklında tut, sonunda soracağım.',
        en: 'Remember the number, I will ask at the end.',
      },
    ],
  },
  {
    id: 'j-course',
    band: '6-9',
    category: 'move',
    minutes: 9,
    stars: 9,
    emoji: '🏃',
    count: { min: 10, max: 25 },
    needs: { move: ['rep'], place: ['roomy'] },
    title: {
      az: '{{count}} dəfə, dayanmadan',
      tr: '{{count}} kere, durmadan',
      en: '{{count}} in a row',
    },
    body: {
      az: '{{place}} {{count}} dəfə {{move}}. Telefonu cibinə qoy, hərəkəti özü sayacaq.',
      tr: '{{place}} {{count}} kere {{move}}. Telefonu cebine koy, hareketi kendi sayar.',
      en: '{{move}} {{count}} times {{place}}. Put the phone in your pocket and it counts the moving.',
    },
  },
  {
    id: 'j-build',
    band: '6-9',
    category: 'create',
    minutes: 14,
    stars: 14,
    emoji: '🔧',
    proof: 'photo',
    needs: { thing: ['build'], theme: ['maker'] },
    title: { az: '{{thing}} ilə qur', tr: '{{thing}} ile yap', en: 'Build with {{things}}' },
    body: {
      az: '{{theme}} düşünərək yalnız {{thing}} ilə bir şey qur. Bitirəndə şəklini çək.',
      tr: '{{theme}} düşünerek sadece {{thing}} ile bir şey yap. Bitince fotoğrafını çek.',
      en: 'Build something out of {{things}}, thinking {{theme}}. Photograph it when it stands up.',
    },
    steps: [
      {
        az: 'Lazım olan hər şeyi əvvəlcə bir yerə yığ.',
        tr: 'İhtiyacın olan her şeyi önce bir araya topla.',
        en: 'Gather everything you need first.',
      },
      {
        az: 'Aşağıdan başla: ən ağır hissə altda olsun.',
        tr: 'Aşağıdan başla: en ağır parça altta olsun.',
        en: 'Start from the bottom: heaviest piece underneath.',
      },
      {
        az: 'Yıxılsa, bir dəfə də yenidən qur. Bu da işin bir hissəsidir.',
        tr: 'Yıkılırsa bir kez daha kur. O da işin parçası.',
        en: 'If it falls, build it once more. That part counts too.',
      },
    ],
  },
  {
    id: 'j-draw',
    band: '6-9',
    category: 'create',
    minutes: 12,
    stars: 12,
    emoji: '✏️',
    proof: 'photo',
    interests: ['drawing'],
    needs: { subject: ['draw'] },
    title: { az: 'Çək: {{subject}}', tr: 'Çiz: {{subject}}', en: 'Draw: {{subject}}' },
    body: {
      az: '{{subject}} çək. Ən azı üç detal əlavə et ki, başqası da başa düşsün.',
      tr: '{{subject}} çiz. En az üç ayrıntı ekle ki başkası da anlasın.',
      en: 'Draw {{subject}}. Add at least three details so somebody else can tell what it is.',
    },
  },
  {
    id: 'j-tidy',
    band: '6-9',
    category: 'calm',
    minutes: 10,
    stars: 10,
    emoji: '🧺',
    proof: 'photo',
    count: { min: 5, max: 12 },
    needs: { thing: ['tidy'], place: ['indoor'] },
    ask: {
      question: {
        az: 'Neçə dənəsini yerinə qoydun?',
        tr: 'Kaç tanesini yerine koydun?',
        en: 'How many did you put away?',
      },
      min: 0,
      max: 30,
      goalFromCount: true,
    },
    title: { az: 'Sahəni səliqəyə sal', tr: 'Alanı topla', en: 'Clear the spot' },
    body: {
      az: '{{place}} {{count}} {{thing}} yerinə qoy. Sonra şəklini çək.',
      tr: '{{place}} {{count}} {{thing}} yerine koy. Sonra fotoğrafını çek.',
      en: 'Put {{count}} {{things}} away {{place}}. Photograph it after.',
    },
  },
  {
    id: 'j-help',
    band: '6-9',
    category: 'social',
    minutes: 12,
    stars: 12,
    emoji: '🤝',
    needs: { place: ['room'] },
    title: { az: 'Bir əl tut', tr: 'Bir el at', en: 'Lend a hand' },
    body: {
      az: '{{place}} bir işi {{person}} birlikdə gör. Hansı işi seçmək sənə qalıb.',
      tr: '{{place}} bir işi {{person}} birlikte yap. Hangi iş olduğunu sen seç.',
      en: 'Do one job {{place}} {{person}}. You choose which job.',
    },
  },
  {
    id: 'j-sort',
    band: '6-9',
    category: 'calm',
    minutes: 8,
    stars: 8,
    emoji: '🧮',
    count: { min: 6, max: 14 },
    needs: { thing: ['sortable', 'small'] },
    ask: {
      question: {
        az: 'Neçə qrupa ayırdın?',
        tr: 'Kaç gruba ayırdın?',
        en: 'How many groups did you make?',
      },
      min: 1,
      max: 10,
    },
    title: { az: 'Qruplara ayır', tr: 'Grupla', en: 'Sort them' },
    body: {
      az: '{{count}} {{thing}} tap və qruplara ayır. Qaydanı özün seç: rəng, ölçü, nə istəsən.',
      tr: '{{count}} {{thing}} bul ve gruplara ayır. Kuralı sen seç: renk, boyut, ne istersen.',
      en: 'Find {{count}} {{things}} and sort them into groups. Your rule: colour, size, whatever you pick.',
    },
  },
  {
    id: 'j-story',
    band: '6-9',
    category: 'social',
    minutes: 10,
    stars: 10,
    emoji: '📖',
    interests: ['books'],
    needs: { subject: ['tell'] },
    title: { az: 'Bir hekayə uydur', tr: 'Bir hikaye uydur', en: 'Make up a story' },
    body: {
      az: '{{subject}} bir hekayənin qəhrəmanı et və {{person}} danış.',
      tr: '{{subject}} bir hikayenin kahramanı yap ve {{person}} anlat.',
      en: 'Make {{subject}} the hero of a story, then tell it {{person}}.',
    },
  },
  {
    id: 'j-outdoor',
    band: '6-9',
    category: 'outdoor',
    minutes: 15,
    stars: 15,
    emoji: '🌳',
    place: 'outdoor',
    proof: 'photo',
    measure: 'none',
    count: { min: 3, max: 7 },
    needs: { thing: ['nature'], place: ['outdoor'] },
    ask: {
      question: {
        az: 'Neçə fərqli dənə tapdın?',
        tr: 'Kaç farklı tane buldun?',
        en: 'How many different ones did you find?',
      },
      min: 0,
      max: 20,
      goalFromCount: true,
    },
    title: { az: 'Çölə çıx: {{thing}}', tr: 'Dışarı çık: {{thing}}', en: 'Outside: {{things}}' },
    body: {
      az: '{{place}} bir-birindən fərqli {{count}} {{thing}} tap. Ən maraqlısının şəklini çək.',
      tr: '{{place}} birbirinden farklı {{count}} {{thing}} bul. En ilgincinin fotoğrafını çek.',
      en: 'Find {{count}} different {{things}} {{place}}. Photograph the most interesting one.',
    },
  },
  {
    id: 'j-challenge',
    band: '6-9',
    category: 'move',
    minutes: 8,
    stars: 8,
    emoji: '⏱️',
    count: { min: 6, max: 15 },
    needs: { thing: ['many', 'small'], place: ['roomy'], twist: ['rule'] },
    title: { az: 'Sürət yarışı', tr: 'Hız yarışı', en: 'Speed run' },
    body: {
      az: '{{place}} {{count}} {{thing}} bir-bir daşı, {{twist}}. Sonra hamısını geri qaytar.',
      tr: '{{place}} {{count}} {{thing}} tek tek taşı, {{twist}}. Sonra hepsini geri götür.',
      en: 'Carry {{count}} {{things}} one at a time {{place}}, {{twist}}. Then take them all back.',
    },
  },

  /* --------------------------------------------------------------- 10 to 14 */
  {
    id: 't-focus',
    band: '10-14',
    category: 'calm',
    minutes: 20,
    stars: 18,
    emoji: '⏳',
    needs: { subject: ['work'] },
    note: {
      prompt: {
        az: 'Nə üzərində işlədin, harada dayandın?',
        tr: 'Ne üzerinde çalıştın, nerede bıraktın?',
        en: 'What did you work on, and where did you stop?',
      },
      minChars: 12,
    },
    title: { az: 'Bir blok', tr: 'Bir blok', en: 'One block' },
    body: {
      az: '{{subject}} götür və 20 dəqiqə üzərində işlə. Telefonu üzüaşağı qoy, saat özü sayacaq.',
      tr: '{{subject}} ele al ve 20 dakika üzerinde çalış. Telefonu yüzüstü koy, saati kendi tutar.',
      en: 'Take {{subject}} and work on it for 20 minutes. Put the phone face down and it keeps the time.',
    },
  },
  {
    id: 't-move',
    band: '10-14',
    category: 'move',
    minutes: 12,
    stars: 12,
    emoji: '🏃',
    count: { min: 20, max: 40 },
    needs: { move: ['rep'], place: ['roomy'] },
    title: { az: '{{count}} təkrar', tr: '{{count}} tekrar', en: '{{count}} reps' },
    body: {
      az: '{{place}} {{count}} dəfə {{move}}. İstəsən iki yerə böl.',
      tr: '{{place}} {{count}} kere {{move}}. İstersen ikiye böl.',
      en: '{{move}} {{count}} times {{place}}. Split it into two sets if you want.',
    },
  },
  {
    id: 't-make',
    band: '10-14',
    category: 'create',
    minutes: 25,
    stars: 22,
    emoji: '🛠️',
    proof: 'photo',
    needs: { thing: ['craft'] },
    title: { az: 'Bir şey düzəlt', tr: 'Bir şey yap', en: 'Make something' },
    body: {
      az: '{{thing}} işlədərək işlək bir şey düzəlt. Nəyi həll etdiyini bilərək başla.',
      tr: '{{thing}} kullanarak işe yarayan bir şey yap. Neyi çözdüğünü bilerek başla.',
      en: 'Make something that actually works, using {{things}}. Start knowing what problem it solves.',
    },
    steps: [
      {
        az: 'Nə düzəltdiyini bir cümlə ilə yaz.',
        tr: 'Ne yaptığını tek cümleyle yaz.',
        en: 'Write down in one sentence what you are making.',
      },
      {
        az: 'Düzəlt. İlk variant pis olacaq, bu normaldır.',
        tr: 'Yap. İlk hali kötü olacak, bu normal.',
        en: 'Make it. The first version will be bad, that is normal.',
      },
      {
        az: 'Sına və bir şeyi dəyiş.',
        tr: 'Dene ve bir şeyi değiştir.',
        en: 'Test it and change one thing.',
      },
    ],
  },
  {
    id: 't-home',
    band: '10-14',
    category: 'social',
    minutes: 20,
    stars: 18,
    emoji: '🏠',
    needs: { place: ['room'] },
    title: { az: 'Sənin üzərinə düşən', tr: 'Senin payına düşen', en: 'Your share' },
    body: {
      az: '{{place}} bir işi soruşmadan gör. Kiminsə xatırlatmasını gözləmə.',
      tr: '{{place}} bir işi sorulmadan yap. Kimsenin hatırlatmasını bekleme.',
      en: 'Do one job {{place}} before anybody asks. No reminder needed.',
    },
  },
  {
    id: 't-outdoor',
    band: '10-14',
    category: 'outdoor',
    minutes: 20,
    stars: 18,
    emoji: '🚶',
    place: 'outdoor',
    needs: { place: ['outdoor'] },
    title: { az: 'Çöldə 20 dəqiqə', tr: 'Dışarıda 20 dakika', en: '20 minutes outside' },
    body: {
      az: '{{place}} 20 dəqiqə keçir. Telefon cibdə, addımlar özü sayılır.',
      tr: '{{place}} 20 dakika geçir. Telefon cepte, adımlar kendi sayılır.',
      en: 'Spend 20 minutes {{place}}. Phone in your pocket, the steps count themselves.',
    },
  },
  {
    id: 't-plan',
    band: '10-14',
    category: 'calm',
    minutes: 10,
    stars: 10,
    emoji: '🗒️',
    needs: { subject: ['work'] },
    note: {
      prompt: {
        az: 'Üç addım yaz. Hər biri bir sətir.',
        tr: 'Üç adım yaz. Her biri bir satır.',
        en: 'Write three steps. One per line.',
      },
      lines: 3,
      minChars: 15,
    },
    title: { az: 'Plan qur', tr: 'Plan kur', en: 'Make a plan' },
    body: {
      az: '{{subject}} üç addıma böl. Birincisi bu həftə bitəcək qədər kiçik olsun.',
      tr: '{{subject}} üç adıma böl. İlki bu hafta bitecek kadar küçük olsun.',
      en: 'Break {{subject}} into three steps. Make the first one small enough to finish this week.',
    },
  },
  {
    id: 't-teach',
    band: '10-14',
    category: 'social',
    minutes: 15,
    stars: 14,
    emoji: '🗣️',
    title: { az: 'Öyrət', tr: 'Öğret', en: 'Teach it' },
    body: {
      az: 'Bacardığın bir şeyi {{person}} öyrət. Sonda özləri etsinlər.',
      tr: 'Yapabildiğin bir şeyi {{person}} öğret. Sonunda kendileri yapsın.',
      en: 'Teach something you can do {{person}}. They should do it themselves at the end.',
    },
  },
  {
    id: 't-clear',
    band: '10-14',
    category: 'calm',
    minutes: 15,
    stars: 14,
    emoji: '📦',
    proof: 'photo',
    count: { min: 5, max: 15 },
    needs: { thing: ['tidy'], place: ['indoor'] },
    avoids: { thing: ['small'] },
    ask: {
      question: {
        az: 'Neçə dənə yığışdırdın?',
        tr: 'Kaç tane kaldırdın?',
        en: 'How many did you clear?',
      },
      min: 0,
      max: 40,
      goalFromCount: true,
    },
    title: { az: 'Yeri boşalt', tr: 'Yeri boşalt', en: 'Clear the space' },
    body: {
      az: '{{place}} {{count}} {{thing}} yığışdır. Əvvəlini və sonrasını çək.',
      tr: '{{place}} {{count}} {{thing}} kaldır. Öncesini ve sonrasını çek.',
      en: 'Clear {{count}} {{things}} {{place}}. Photograph it before and after.',
    },
  },
];
